baseURL = 'https://hacksies.com/'
languageCode = 'en-us'
title = 'Hacksies'
theme = 'paper'

[markup.goldmark.renderer]
unsafe = true

ignoreFiles = ["figures/"]

[markup.goldmark.extensions.passthrough]
enable = true
[markup.goldmark.extensions.passthrough.delimiters]
block = [['$$', '$$'], ['\\[', '\\]']]
inline = [['$', '$'], ['\\(', '\\)']]